FROM jakobjkolb/airflow:latest

RUN chown -R airflow:airflow /usr/local/src

USER root

RUN mkdir ../../libs
RUN mkdir ../../libs/database

USER airflow

ARG YOUR_ENV

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on

WORKDIR /opt/airflow/

ADD projects/airflow/airflow.cfg projects/airflow/poetry.lock projects/airflow/pyproject.toml /opt/airflow/

# copy libs into the container, so their paths exist for editable installs
COPY libs/database ../../libs/database

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

ENV PYTHONPATH "${PYTHONPATH}:/opt/airflow/dags"