FROM jakobjkolb/airflow:latest

RUN chown -R airflow:airflow /usr/local/src

USER airflow

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    POETRY_VIRTUALENVS_CREATE=false

WORKDIR /opt/airflow/

ADD airflow.cfg pyproject.toml /opt/airflow/

RUN poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi

ENV PYTHONPATH "${PYTHONPATH}:/opt/airflow/dags"