FROM jakobjkolb/airflow:latest

RUN chown -R airflow:airflow /usr/local/src

USER airflow

ARG YOUR_ENV

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on

WORKDIR /opt/airflow/

ADD airflow.cfg poetry.lock pyproject.toml /opt/airflow/

RUN pip install --requirement <(poetry export  --without-hashes --dev --format requirements.txt)

ENV PYTHONPATH "${PYTHONPATH}:/opt/airflow/dags"