[build]
publish = "target"
command = """
echo -n "$GPG_KEY" | tr ',' '\n' | gpg --import

git clone https://github.com/sobolevn/git-secret.git git-secret
cd git-secret && make build
PREFIX="." make install
cd ../../../
ls
gpg --list-keys
./services/dbt/git-secret/bin/git-secret whoknows
./services/dbt/git-secret/bin/git-secret reveal -f
cd services/dbt

apt install openvpn
echo "$VPN_SECRET" > vpn_secrets.conf

openvpn --config ../../.github/workflows/hu-berlin.ovpn --auth-user-pass vpn_secrets.conf &&
sleep 20

pip install poetry
poetry install -v
make build-docs
"""