[build]
publish = "target"
command = """
echo -n "$GPG_KEY" | tr ',' '\n' | gpg --import
apt install git-secret
git-secret reveal -f

apt install openvpn
echo "$VPN_SECRET" > vpn_secrets.conf

openvpn --config ../../.github/workflows/hu-berlin.ovpn --auth-user-pass vpn_secrets.conf &&
sleep 20

pip install poetry
poetry install -v
make build-docs
"""