data-pipelines:
  target: postgres
  outputs:
    postgres:
      type: postgres
      threads: 4
      host: "{{ env_var('TARGET_DB_HOSTNAME') }}"
      port: "{{env_var('TARGET_DB_PORT') | as_number }}"
      user: "{{ env_var('TARGET_DB_USER') }}"
      pass: "{{ env_var('TARGET_DB_PW') }}"
      dbname: "{{ env_var('TARGET_DB') }}"
      schema: "{{ env_var('TARGET_DB_SCHEMA') }}"
