---
version: '3'

services:
  clickhouse:
    hostname: "${CLICKHOUSE_HOSTNAME}"
    container_name: "clickhouse-db-testing"
    image: yandex/clickhouse-server:latest
    volumes:
      - ./docker/clickhouse/config.yaml:/etc/clickhouse-server/config.yaml
      - ./docker/clickhouse/users.yaml:/etc/clickhouse-server/users.d/users.yaml
      - ./docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse-db-volume:/var/lib/clickhouse:rw
    environment:
      CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8123/ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "9000:9000" # for native clickhouse client
      - "8123:8123" # for HTML client

volumes:
  clickhouse-db-volume:
