FROM jakobjkolb/airflow:latest

USER root

RUN chown -R airflow:root /usr/local/src

USER airflow

ARG YOUR_ENV

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on

WORKDIR /opt/airflow/

ADD services/airflow/airflow.cfg services/airflow/poetry.lock services/airflow/pyproject.toml /opt/airflow/

# copy libs into the container, so their paths exist for editable installs
COPY libraries ../../libraries

RUN pip install --requirement <(poetry export --without-hashes --dev --format requirements.txt)

ENV PYTHONPATH "${PYTHONPATH}:/opt/airflow/dags"