# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-ornt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_KEY" | base64 --decode | gpg --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Reveal secrets
        run: |
          sudo apt install git-secret
          git-secret reveal
      - name: Install openvpn
        run: sudo apt install openvpn
      - name: Write vpn secrets to file
        env:
          VPN_SECRET: ${{secrets.VPN_SECRET}}
        run: 'echo "$VPN_SECRET" > vpn_secrets.conf'
        shell: bash
      - name: Connect to VPN
        run: |
          sudo openvpn --config .github/workflows/hu-berlin.ovpn --auth-user-pass vpn_secrets.conf &&
          sleep 20
      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - name: Login to ornt, build and setup
        run: |
          cat deploy.sh | ssh -A -o "StrictHostKeyChecking no" kolb@ornt.biologie.hu-berlin.de