name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'true'

jobs:
  deploy-to-ornt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/airflow

    steps:
      - uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_KEY" | base64 --decode | gpg --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Reveal secrets
        run: |
          sudo apt install git-secret
          git-secret reveal

      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install openvpn
        run: sudo apt install openvpn

      - name: Write vpn secrets to file
        env:
          VPN_SECRET: ${{secrets.VPN_SECRET}}
        run: 'echo "$VPN_SECRET" > vpn_secrets.conf'
        shell: bash

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Connect to VPN
        run: |
          sudo openvpn --config services/airflow/.github/workflows/hu-berlin.ovpn --auth-user-pass vpn_secrets.conf &&
          sleep 20

      - name: Login to ornt, build and setup
        run: |
          cat services/airflow/deploy.sh | ssh -A -o "StrictHostKeyChecking no" kolb@ornt.biologie.hu-berlin.de