# This is a basic workflow to help you get started with Actions

name: lib/database

on:
  push:
    tags:
      - 'v*'
    paths: ["libraries/clickhouse-helpers/**"]
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: [self-hosted, docker]
    defaults:
      run:
        working-directory: ./libraries/clickhouse-helpers

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2
      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        env:
          PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
        run:  |
          poetry run migrate-clickhouse 
          --host devi.biologie.hu-berlin.de 
          --port 9000
          --database rocs 
          --user ornt 
          --password ${PASSWORD}
