# This is a basic workflow to help you get started with Actions

name: lib/database CD

on:
  push:
    tags:
      - 'v*'
    paths: ["libraries/postgres-helpers/**"]
  workflow_dispatch:


jobs:
  run-migrations:
    runs-on: [self-hosted, docker]
    defaults:
      run:
        working-directory: ./libraries/postgres-helpers

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2
      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        env:
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
        run:  |
          poetry run yoyo apply \
          --no-config-file \
          --database ${DATABASE_CONNECTION_STRING} \
          postgres_helpers/migrations/migration_files
