# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  # shedule every week
  schedule:
      - cron: '0 0 * * 0'
  # on push to main branch
  push:
    tag:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # manually
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Airflow Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get git tag
        uses: little-core-labs/get-git-tag@v3.0.2

      - name: Build docker image
        run: docker build -t rocs-airflow:$GIT_TAG_NAME . -f services/airflow/docker/airflow/Dockerfile

      - name: Publish docker image to github packages
        if: github.event_name == 'schedule' || github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag rocs-airflow:$GIT_TAG_NAME ghcr.io/${{ github.repository_owner }}/rocs-airflow:$GIT_TAG_NAME
          docker push ghcr.io/${{ github.repository_owner }}/rocs-airflow:$GIT_TAG_NAME
